### ISSUE TITLE
Add docx to pdf converter

### ISSUE THREAD

**Issue by conig** [Motivation-and-Behaviour/tidyMB#12]
To facilitate pdf page look-ups it would be useful to include a docx to PDF conversion function. Perhaps we could use pandoc?

**Comment by conig** [comment]
Have added support for windows requiring a separate install of docto. Will also need a solution for mac users.

**Comment by pdparker** [comment]
The current template can be knit to a word doc. We currently knit the template to html and pdf. @tarensanders should not be too hard to add knit to word doc in the yaml also?

**Comment by conig** [comment]
Currently it's only possible to automatically detect page numbers for quotes if page numbers are provided. I was thinking having a function to convert word docs to pdf would help make workflows a bit easier, but as I can't support mac I've relegated it to be an internal function.
