### ISSUE TITLE
Remove revise functions and add revise as a dependency?

### ISSUE THREAD

**Issue by tarensanders** [Motivation-and-Behaviour/tidyMB#22]
@conig I'm just doing a bit of a tidy up of this package. Does it make sense to remove the revise functions that are here and just use your package instead? Is there anything here that isn't in revise?

**Comment by conig** [comment]
Absolutely go to town. As far as I'm aware I've taken everything I needed. But if you forward through the commit once you push it I'll double check the difference log in case I missed something.

**Comment by tarensanders** [comment]
Thanks mate. It's commit 4ad7653
