### ISSUE TITLE
[question] Inserting divs to rmd without adding paragraph breaks

### ISSUE THREAD

**Issue by conig** [Motivation-and-Behaviour/tidyMB#8]
Thanks for this package, read_manuscript() works great! I find that inserting divs into a papaja rmarkdown creates paragraph breaks. Is there a way to get around this?

Raw code:
```
...which has been linked to unhealthy alcohol use [@kingIndigenousHealthPart2009].<div id="test"> Australian Aboriginal and Torres Strait Islander peoples ('Indigenous Australians') have described unhealthy alcohol use as an area of concern</div>. [@ministerialcouncilondrugstrategyNationalDrugStrategy2003].
```
Before:
![image](https://user-images.githubusercontent.com/12742211/97646108-e2618c80-1aa2-11eb-83e1-a49e9757e255.png)

After:
![image](https://user-images.githubusercontent.com/12742211/97646137-fc02d400-1aa2-11eb-9943-bae62122c650.png)

**Comment by pdparker** [comment]
@conig I would recommend use span tags rather than div.

**Comment by conig** [comment]
@pdparker thanks, working perfectly.
Great function, will definitely use!
